# Generated by Django 3.0.8 on 2020-09-14 09:56

from django.db import migrations, models
import slider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=slider.models.upload_image_path)),
            ],
        ),
    ]
