# Generated by Django 3.0.8 on 2020-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_billing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
