# Generated by Django 3.0.8 on 2020-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200916_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='is_accept_terms',
        ),
        migrations.AddField(
            model_name='billing',
            name='is_in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
