# Generated by Django 3.0.8 on 2020-09-14 11:33

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200914_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_image_path_gallery),
        ),
    ]
